### PR TITLE
Build minisatip with DVB-CSA support

### PR DESCRIPTION
**Pull request by Jalle19**

### CODE REVIEW

**Comment by Jalle19** [comment]
@SmoothMC can you try this build? https://github.com/Jalle19/satip-axe/releases/tag/dvbcsa-preview1 there are the firmware files

**Comment by Jalle19** [comment]
@SmoothMC can you try this build? You're the one who wanted it.

**Comment by Jalle19** [comment]
@SmoothMC ping. I'm closing this later if you're not going to test the build.

**Comment by SmoothMC** [comment]
Hey...sry for Late reply.
I Test it and it running stable. I use it with an external instance of oscam on my homserver. But More than 2 parallel decrypted Streams are not possible.

Thx for build

**Comment by Jalle19** [comment]
> I Test it and it running stable. I use it with an external instance of oscam on my homserver. But More than 2 parallel decrypted Streams are not possible.

Thanks for reporting back! I'll merge this and add a note in the release notes that DVB-CSA support is unsupported but should work for 1-2 streams.

**Pull request merged**
