### PR TITLE
Bump software to latest

### PR DESCRIPTION
**Pull request by Xeroxxx**
minisatip 1.1.44
busybox 1.34.0
dropbear 2020.81
ethtool 4.19
libtirpc 1.3.2
rpcbind 1.2.6
nano 2.8.7
oscam 11696

Kernel is more close to latest 2.6 kernel .71 than .42 (with some exceptions that break building the kernel)
Verified by applying kernel patches.

### CODE REVIEW

**Comment by Jalle19** [comment]
This got closed automatically because you opened the PR against a feature branch, not `master`.

Anyway, did you try building this?

The kernel version is not bumped simply by editing the Makefile - a copy of that particular kernel is shipped in this repository and that's what gets compiled. Editing the Makefile won't change the source in any meaningful way, that's why the patches still applied.

**Comment by Xeroxxx** [comment]
I build this yes.

Regarding the kernel, as I said. I tried to apply all patches from .43 to .71. 90% of the patches already applied. The parts of the patches not applied, breaking the kernel build.

**Comment by Xeroxxx** [comment]
Additonally I should clarifiy "latest" means "latest supported and working for 2.6"

**Comment by Jalle19** [comment]
You haven't actually bumped the kernel version, you've only changed that one number in that one file. You need to replace the whole contents of the `kernel` directory with a newer kernel if you actually want to use a newer one.

I'l not sure any of this is worth the effort? This device is an appliance and the latest 2.6 kernel is still ancient no matter what 🤷

**Comment by Jalle19** [comment]
@Xeroxxx sorry, I misunderstood you completely earlier! So the kernel shipped here is indeed version 71, not 42 like the Makefile says.

Did you apply Linux upstream patches or stmlinux patches? The original repository is gone but there's a mirror on GitHub (on the phone so I can't find it easily).

@timehlers I have no idea :/

@Xeroxxx can you rebase and reopen this PR against master so that GitHub Actions trigger a build for it?

**Comment by Xeroxxx** [comment]
> I don't understand how this should work with the closed source kernel modules built for 2.6.32.42_stm24_0208-idl4k_7108. I see these modules in the directory "patches" also in your branch built for this version. I don't think, that there is any weak-update mechanism active to support loading modules built for older kernels, or am I wrong?

I think the kernel was always .71 even the kernel modules. The patchfiles didn't update the version number while being applied. So basically the naming 2.6.32.42 is wrong. As I said I patched the kernel to .71 and 90% of lines of the patches have already been applied. The lines that haven't been applied are obviously because I applied mainstream instead of stm patches.

**Comment by Xeroxxx** [comment]
Dropbear works fine, you place this as dropin replacement to update. Only problem seems busybox for now.

**Comment by Jalle19** [comment]
I upgraded Dropbear in #31

**Pull request closed without merging**
