### PR TITLE
Build 22

### PR DESCRIPTION
**Pull request by Jalle19**
https://github.com/Jalle19/satip-axe/releases/tag/build22-rc1

### CODE REVIEW

**Comment by Jalle19** [comment]
@estimadarocha @apt1506 @ncurado can you please try firmware? The bug you reported in #28 should now be fixed. Please read the CHANGELOG if you're using the `-U` option.

**Comment by ncurado** [comment]
I've moved away from the -U option and am now using -A. I will try this build tonight; unfortunately, I won't have time before that.

**Comment by Jalle19** [comment]
I'm running this myself since this morning, so far so good.

**Comment by ncurado** [comment]
Managed to do some testing during my lunch hour. All seems to be working fine.

**Comment by ncurado** [comment]
My setup is now experiencing some issues with some blank channels, probably related to TVHeadEnd pid settings. I'll continue testing as soon as possible.

**Comment by ncurado** [comment]
Sorted the configuration. All working as expected.

**Comment by Jalle19** [comment]
Good to hear!

**Comment by Jalle19** [comment]
Trying one additional tweak/fix to minisatip, will include it in this build if it seems to work.

**Comment by ncurado** [comment]
Are you thinking of bumping minisatip to v1.2.10?

**Comment by Jalle19** [comment]
I'm looking to get https://github.com/catalinii/minisatip/pull/984 merged and included first

**Comment by estimadarocha** [comment]
@Jalle19 working as expected!

**Comment by Jalle19** [comment]
Made a second release candidate, https://github.com/Jalle19/satip-axe/releases/tag/build22-rc2. Been running it for a day or two myself.

**Comment by ncurado** [comment]
Just installed. Everything seems to be working as expected. I'm currently streaming two channels to different devices with no issues.

**Comment by roisiano** [comment]
Hello:

I'm using [Build 21 (Mar 26 2022)](https://github.com/Jalle19/satip-axe/releases/tag/build21) in my Digibit R1 with these options:
MINISATIP_OPTS="-Z 0,2:300 -j 0:0-1210,2:1-1420 --dmx-source 0:0,1:1,2:0,3:3 --diseqc 1:4-0,3:4-0" 

LNB Unicable from Astra 19.2 connected to input cable 1 of Digibit R1.
diseqC 19.2E / 30W / 13E / 23.5E connected to input cable 2 of Digibit R1.
diseqC 19.2E / 30W / 13E / 23.5E (other different) connected to input cable 4 of Digibit R1.  

I explained here before: 
https://github.com/Jalle19/satip-axe/issues/13

I use --dmx-source option to "tell" Digibit R1 to use input cable 1 for tuners 0 and 2, input cable 2 for tuner 1, input cable 4 for tuner 3. 

I have read that -U options does NOT work anymore. Does --dmx-source option work with Build 22 as it works with Build 21? 

I suppose that unicable option is not compatible with -A.

**Comment by Jalle19** [comment]
@roisiano `--dmx-source` and `-U` is the same option, so no it won't work on Build 22. You have to use `-A` instead.

Personally I use `-S 0-2:0,3:3 -A 0:0:0,0:1:0,0:2:0,1:3:1` to say that tuners 0, 1 and 2 should use input 0, while tuner 3 should use input 3.

**Comment by Jalle19** [comment]
https://github.com/Jalle19/satip-axe/releases/tag/build22

**Comment by Jalle19** [comment]
Check the log for "unrecognized option" warnings

**Pull request merged**
