### PR TITLE
Resurrect upgrade-fw, adapt it for local flashing only, downgrade minisatip

### PR DESCRIPTION
**Pull request by Jalle19**

### CODE REVIEW

**Comment by Jalle19** [comment]
@estimadarocha can you test this build if I provide a firmware file for you to flash? I've tried it on one of my own devices and it seems to work fine, just make sure `upgrade-fw` actually says the write was successful (usually it needs one retry to fully flash the firmware).

**Comment by Jalle19** [comment]
@estimadarocha which exact build are you on? Do you have the `upgrade-fw` script available on the device?

**Comment by estimadarocha** [comment]
After a few minutes driving got them Over my house... Eheheh Will try later today

**Comment by estimadarocha** [comment]
@Jalle19  is this the same tool? because it doesn't show progress and it failed or not like the previous versions....

upgrade-fw satip-axe-202203241658-21-rc1.fw
Preparing to flash - killing minisatip, unmounting USB sticks
umount: can't unmount /media/*: No such file or directory
Verifying... Dumping current flash contents.
Verify OK. Flash write successful.

**Comment by ncurado** [comment]
I've tested the RC with three encrypted (decryption happened outside Digibit R1) concurrent streams (via unicable). All worked fine.

**Comment by estimadarocha** [comment]
@Jalle19 is it possible to build also with upgrade-fw and last minisatip to be able to test if it works or not like reported?

**Comment by ncurado** [comment]
@estimadarocha , the RC includes:
- minisatip 1.1.83
- upgrade-fw
I flashed my R1 via USB.

**Comment by estimadarocha** [comment]
@ncurado yes i know... i am using that version also... my request was a 1.1.87 with upgrade-fw included 

just to try make some logging to see what's the real problem between 1.1.87 and 1.1.83...

**Comment by Jalle19** [comment]
> @Jalle19 is this the same tool? because it doesn't show progress and if failed or not like the previous versions

It's the same tool. Sometimes the flashing works on the first try, sometimes it doesn't. I don't really know what's up with it but the important thing is that it works.

**Pull request merged**
